## GENERATED by tools/gen_raw.py from wgrender's include/*.h: do not edit, run the tool.
##
## The C API as is: C names, C types. Most code wants the wrappers in `wgr` instead
## (Nim types, closures). Declarations import from wgrender's public headers
## (`header: "wgr.h"`); tools/coverage.py --check checks every one against them.
##
## wgrender 0.0.1, 34 headers.
## wgrender-headers: 017dae86087a6947

import ./internal/build # compiles wgrender into the program, from its build.json

type
  WgrHandle* = cuint
  WgrColor* = uint32

  # wgrender passes strings to callbacks as `const char*`; Nim's cstring is `char*`,
  # and clang (emcc) rejects the mismatched callback type. Convert with `cstring(s)`.
  WgrConstCstring* {.importc: "const char*", nodecl.} = distinct cstring

  CVec2* {.importc: "vec2_t", bycopy, header: "wgr.h".} = object
    x*: cfloat
    y*: cfloat

  CMouseState* {.importc: "wgr_mouse_state_t", bycopy, header: "wgr.h".} = object
    x*: cint
    y*: cint
    wheel*: cfloat
    wheel_x*: cfloat
    left*: cint
    right*: cint
    middle*: cint
    buttons*: array[3, cint]
    dx*: cint
    dy*: cint

  CKeyboardState* {.importc: "wgr_keyboard_state_t", bycopy, header: "wgr.h".} = object
    max_num_keys*: cint
    keys*: array[512, cint]
    pressed_key*: cint
    pressed_char*: cint
    num_pressed_keys*: cint
    pressed_keys*: array[32, cint]
    num_pressed_chars*: cint
    pressed_chars*: array[32, cint]

  CVec3* {.importc: "vec3_t", bycopy, header: "wgr.h".} = object
    x*: cfloat
    y*: cfloat
    z*: cfloat

  CVec4* {.importc: "vec4_t", bycopy, header: "wgr.h".} = object
    x*: cfloat
    y*: cfloat
    z*: cfloat
    w*: cfloat

  CMatrix* {.importc: "matrix_t", bycopy, header: "wgr.h".} = object
    m0*: cfloat
    m4*: cfloat
    m8*: cfloat
    m12*: cfloat
    m1*: cfloat
    m5*: cfloat
    m9*: cfloat
    m13*: cfloat
    m2*: cfloat
    m6*: cfloat
    m10*: cfloat
    m14*: cfloat
    m3*: cfloat
    m7*: cfloat
    m11*: cfloat
    m15*: cfloat

  CQuat* {.importc: "quat_t", bycopy, header: "wgr.h".} = object
    x*: cfloat
    y*: cfloat
    z*: cfloat
    w*: cfloat

  CRect* {.importc: "rect_t", bycopy, header: "wgr.h".} = object
    x*: cfloat
    y*: cfloat
    width*: cfloat
    height*: cfloat

  CPickResult* {.importc: "wgr_pick_result_t", bycopy, header: "wgr.h".} = object
    hit*: bool
    handle*: WgrHandle
    distance*: cfloat
    point_local*: CVec3
    point_world*: CVec3
    normal_local*: CVec3
    normal_world*: CVec3

  CTouch* {.importc: "wgr_touch_t", bycopy, header: "wgr.h".} = object
    id*: cint
    x*: cfloat
    y*: cfloat
    dx*: cfloat
    dy*: cfloat
    state*: cint

  CTouchGesture* {.importc: "wgr_touch_gesture_t", bycopy, header: "wgr.h".} = object
    active*: bool
    x*: cfloat
    y*: cfloat
    dx*: cfloat
    dy*: cfloat
    scale*: cfloat
    rotation*: cfloat

  CPickStats* {.importc: "wgr_pick_stats_t", bycopy, header: "wgr.h".} = object
    broadphase_tests*: cint
    broadphase_rejects*: cint
    narrowphase_tests*: cint
    narrowphase_hits*: cint

  WgrAssetCallbackFn* = proc (path: WgrConstCstring; user_data: pointer) {.cdecl.}
  WgrAssetFetchFn* = proc (request: WgrHandle; url: WgrConstCstring; dest_path: WgrConstCstring; user_data: pointer) {.cdecl.}
  WgrAssetPingFn* = proc (host: WgrConstCstring; milliseconds: cfloat; user_data: pointer) {.cdecl.}
  WgrEventListenerFn* = proc (payload: pointer; user_data: pointer) {.cdecl.}
  WgrTickFn* = proc (dt: cfloat; user_data: pointer) {.cdecl.}
  WgrFrameFn* = proc (dt: cfloat; tick_fraction: cfloat; user_data: pointer) {.cdecl.}
  WgrLifecycleFn* = proc (user_data: pointer) {.cdecl.}

const
  WGR_ALPHA_OPAQUE* = 0.cint
  WGR_ALPHA_MASK* = 1.cint
  WGR_ALPHA_BLEND* = 2.cint
  WGR_ALPHA_ADD* = 3.cint
  WGR_BUTTON_UP* = 0.cint
  WGR_BUTTON_PRESSED* = 1.cint
  WGR_BUTTON_DOWN* = 2.cint
  WGR_BUTTON_RELEASED* = 3.cint
  WGR_ASSET_ADD_TASK_OK* = 0.cint
  WGR_ASSET_ADD_TASK_ERR_INVALID* = (-1).cint
  WGR_ASSET_ADD_TASK_ERR_QUEUE_FULL* = (-2).cint
  WGR_CAMERA3D_PERSPECTIVE* = 0.cint
  WGR_CAMERA3D_ORTHOGRAPHIC* = 1.cint
  WGR_HANDLE_KIND_NONE* = 0.cint
  WGR_HANDLE_KIND_CAMERA3D* = 2.cint
  WGR_HANDLE_KIND_FONT* = 3.cint
  WGR_HANDLE_KIND_TEXTURE* = 4.cint
  WGR_HANDLE_KIND_SPRITE2D* = 5.cint
  WGR_HANDLE_KIND_SPRITE3D* = 6.cint
  WGR_HANDLE_KIND_MODEL* = 7.cint
  WGR_HANDLE_KIND_MESH* = 8.cint
  WGR_HANDLE_KIND_SOUND* = 9.cint
  WGR_HANDLE_KIND_TEXT2D* = 11.cint
  WGR_HANDLE_KIND_SCENE* = 12.cint
  WGR_HANDLE_KIND_SHAPE3D* = 13.cint
  WGR_HANDLE_KIND_TEXT3D* = 14.cint
  WGR_HANDLE_KIND_AUDIO* = 15.cint
  WGR_HANDLE_KIND_LIGHT* = 16.cint
  WGR_HANDLE_KIND_MATERIAL* = 17.cint
  WGR_HANDLE_KIND_ENVIRONMENT* = 18.cint
  WGR_HANDLE_KIND_SHAPE2D* = 19.cint
  WGR_HANDLE_KIND_EMITTER3D* = 20.cint
  WGR_HANDLE_KIND_EMITTER2D* = 21.cint
  WGR_HANDLE_KIND_SHADER* = 22.cint
  WGR_HANDLE_KIND_ASSET_TASK* = 32.cint
  WGR_KEY_SPACE* = 32.cint
  WGR_KEY_APOSTROPHE* = 39.cint
  WGR_KEY_COMMA* = 44.cint
  WGR_KEY_MINUS* = 45.cint
  WGR_KEY_PERIOD* = 46.cint
  WGR_KEY_SLASH* = 47.cint
  WGR_KEY_0* = 48.cint
  WGR_KEY_1* = 49.cint
  WGR_KEY_2* = 50.cint
  WGR_KEY_3* = 51.cint
  WGR_KEY_4* = 52.cint
  WGR_KEY_5* = 53.cint
  WGR_KEY_6* = 54.cint
  WGR_KEY_7* = 55.cint
  WGR_KEY_8* = 56.cint
  WGR_KEY_9* = 57.cint
  WGR_KEY_SEMICOLON* = 59.cint
  WGR_KEY_EQUAL* = 61.cint
  WGR_KEY_A* = 65.cint
  WGR_KEY_B* = 66.cint
  WGR_KEY_C* = 67.cint
  WGR_KEY_D* = 68.cint
  WGR_KEY_E* = 69.cint
  WGR_KEY_F* = 70.cint
  WGR_KEY_G* = 71.cint
  WGR_KEY_H* = 72.cint
  WGR_KEY_I* = 73.cint
  WGR_KEY_J* = 74.cint
  WGR_KEY_K* = 75.cint
  WGR_KEY_L* = 76.cint
  WGR_KEY_M* = 77.cint
  WGR_KEY_N* = 78.cint
  WGR_KEY_O* = 79.cint
  WGR_KEY_P* = 80.cint
  WGR_KEY_Q* = 81.cint
  WGR_KEY_R* = 82.cint
  WGR_KEY_S* = 83.cint
  WGR_KEY_T* = 84.cint
  WGR_KEY_U* = 85.cint
  WGR_KEY_V* = 86.cint
  WGR_KEY_W* = 87.cint
  WGR_KEY_X* = 88.cint
  WGR_KEY_Y* = 89.cint
  WGR_KEY_Z* = 90.cint
  WGR_KEY_LEFT_BRACKET* = 91.cint
  WGR_KEY_BACKSLASH* = 92.cint
  WGR_KEY_RIGHT_BRACKET* = 93.cint
  WGR_KEY_GRAVE_ACCENT* = 96.cint
  WGR_KEY_ESCAPE* = 256.cint
  WGR_KEY_ENTER* = 257.cint
  WGR_KEY_TAB* = 258.cint
  WGR_KEY_BACKSPACE* = 259.cint
  WGR_KEY_INSERT* = 260.cint
  WGR_KEY_DELETE* = 261.cint
  WGR_KEY_RIGHT* = 262.cint
  WGR_KEY_LEFT* = 263.cint
  WGR_KEY_DOWN* = 264.cint
  WGR_KEY_UP* = 265.cint
  WGR_KEY_PAGE_UP* = 266.cint
  WGR_KEY_PAGE_DOWN* = 267.cint
  WGR_KEY_HOME* = 268.cint
  WGR_KEY_END* = 269.cint
  WGR_KEY_CAPS_LOCK* = 280.cint
  WGR_KEY_F1* = 290.cint
  WGR_KEY_F2* = 291.cint
  WGR_KEY_F3* = 292.cint
  WGR_KEY_F4* = 293.cint
  WGR_KEY_F5* = 294.cint
  WGR_KEY_F6* = 295.cint
  WGR_KEY_F7* = 296.cint
  WGR_KEY_F8* = 297.cint
  WGR_KEY_F9* = 298.cint
  WGR_KEY_F10* = 299.cint
  WGR_KEY_F11* = 300.cint
  WGR_KEY_F12* = 301.cint
  WGR_KEY_LEFT_SHIFT* = 340.cint
  WGR_KEY_LEFT_CONTROL* = 341.cint
  WGR_KEY_LEFT_ALT* = 342.cint
  WGR_KEY_LEFT_SUPER* = 343.cint
  WGR_KEY_RIGHT_SHIFT* = 344.cint
  WGR_KEY_RIGHT_CONTROL* = 345.cint
  WGR_KEY_RIGHT_ALT* = 346.cint
  WGR_KEY_RIGHT_SUPER* = 347.cint
  WGR_MOUSE_BUTTON_LEFT* = 0.cint
  WGR_MOUSE_BUTTON_RIGHT* = 1.cint
  WGR_MOUSE_BUTTON_MIDDLE* = 2.cint
  WGR_GAMEPAD_BUTTON_SOUTH* = 0.cint
  WGR_GAMEPAD_BUTTON_EAST* = 1.cint
  WGR_GAMEPAD_BUTTON_WEST* = 2.cint
  WGR_GAMEPAD_BUTTON_NORTH* = 3.cint
  WGR_GAMEPAD_BUTTON_LEFT_BUMPER* = 4.cint
  WGR_GAMEPAD_BUTTON_RIGHT_BUMPER* = 5.cint
  WGR_GAMEPAD_BUTTON_LEFT_TRIGGER* = 6.cint
  WGR_GAMEPAD_BUTTON_RIGHT_TRIGGER* = 7.cint
  WGR_GAMEPAD_BUTTON_BACK* = 8.cint
  WGR_GAMEPAD_BUTTON_START* = 9.cint
  WGR_GAMEPAD_BUTTON_GUIDE* = 10.cint
  WGR_GAMEPAD_BUTTON_LEFT_STICK* = 11.cint
  WGR_GAMEPAD_BUTTON_RIGHT_STICK* = 12.cint
  WGR_GAMEPAD_BUTTON_DPAD_UP* = 13.cint
  WGR_GAMEPAD_BUTTON_DPAD_DOWN* = 14.cint
  WGR_GAMEPAD_BUTTON_DPAD_LEFT* = 15.cint
  WGR_GAMEPAD_BUTTON_DPAD_RIGHT* = 16.cint
  WGR_GAMEPAD_BUTTON_COUNT* = 17.cint
  WGR_GAMEPAD_AXIS_LEFT_X* = 0.cint
  WGR_GAMEPAD_AXIS_LEFT_Y* = 1.cint
  WGR_GAMEPAD_AXIS_RIGHT_X* = 2.cint
  WGR_GAMEPAD_AXIS_RIGHT_Y* = 3.cint
  WGR_GAMEPAD_AXIS_LEFT_TRIGGER* = 4.cint
  WGR_GAMEPAD_AXIS_RIGHT_TRIGGER* = 5.cint
  WGR_GAMEPAD_AXIS_COUNT* = 6.cint
  WGR_LIGHT_DIRECTIONAL* = 0.cint
  WGR_LIGHT_POINT* = 1.cint
  WGR_LIGHT_SPOT* = 2.cint
  WGR_LOGGER_LEVEL_TRACE* = 0.cint
  WGR_LOGGER_LEVEL_DEBUG* = 1.cint
  WGR_LOGGER_LEVEL_INFO* = 2.cint
  WGR_LOGGER_LEVEL_WARN* = 3.cint
  WGR_LOGGER_LEVEL_ERROR* = 4.cint
  WGR_LOGGER_LEVEL_FATAL* = 5.cint
  WGR_TEXTURE_WRAP_REPEAT* = 0.cint
  WGR_TEXTURE_WRAP_CLAMP* = 1.cint
  WGR_TEXTURE_WRAP_MIRROR* = 2.cint
  WGR_TEXTURE_FILTER_LINEAR* = 0.cint
  WGR_TEXTURE_FILTER_NEAREST* = 1.cint
  WGR_MATERIAL_PBR* = 0.cint
  WGR_MATERIAL_UNLIT* = 1.cint
  WGR_MATERIAL_CUSTOM* = 2.cint
  WGR_TONEMAP_NONE* = 0.cint
  WGR_TONEMAP_NEUTRAL* = 1.cint
  WGR_TONEMAP_ACES* = 2.cint
  WGR_SPRITE3D_FACING_CAMERA* = 0.cint
  WGR_SPRITE3D_FACING_CAMERA_FIXED_Y* = 1.cint
  WGR_SPRITE3D_FACING_Y_UP* = 2.cint
  WGR_SPRITE3D_FACING_FREE* = 3.cint
  WGR_TEXT_ALIGN_LEFT* = 0.cint
  WGR_TEXT_ALIGN_CENTER* = 1.cint
  WGR_TEXT_ALIGN_RIGHT* = 2.cint
  WGR_TEXT_ALIGN_TOP* = 3.cint
  WGR_TEXT_ALIGN_MIDDLE* = 4.cint
  WGR_TEXT_ALIGN_BOTTOM* = 5.cint
  WGR_INIT_OK* = 0.cint
  WGR_INIT_ERR_UNKNOWN* = (-1).cint
  WGR_INIT_ERR_ALREADY_INITIALIZED* = (-2).cint
  WGR_INIT_ERR_WINDOW* = (-5).cint
  WGR_COLOR_LIGHTGRAY* = 0xC8C8C8FF'u32
  WGR_COLOR_GRAY* = 0x828282FF'u32
  WGR_COLOR_DARKGRAY* = 0x505050FF'u32
  WGR_COLOR_YELLOW* = 0xFFFF00FF'u32
  WGR_COLOR_GOLD* = 0xFFCB00FF'u32
  WGR_COLOR_ORANGE* = 0xFFA100FF'u32
  WGR_COLOR_PINK* = 0xFF6DC2FF'u32
  WGR_COLOR_RED* = 0xE62937FF'u32
  WGR_COLOR_MAROON* = 0xBE212DFF'u32
  WGR_COLOR_GREEN* = 0x00E430FF'u32
  WGR_COLOR_LIME* = 0x009E2FFF'u32
  WGR_COLOR_DARKGREEN* = 0x00752CFF'u32
  WGR_COLOR_SKYBLUE* = 0x66BFFFFF'u32
  WGR_COLOR_BLUE* = 0x0079F1FF'u32
  WGR_COLOR_DARKBLUE* = 0x0052ACFF'u32
  WGR_COLOR_PURPLE* = 0xC87AFFFF'u32
  WGR_COLOR_VIOLET* = 0x873CBEFF'u32
  WGR_COLOR_DARKPURPLE* = 0x701F7EFF'u32
  WGR_COLOR_BEIGE* = 0xD3B083FF'u32
  WGR_COLOR_BROWN* = 0x7F6A4FFF'u32
  WGR_COLOR_DARKBROWN* = 0x4C3F2FFF'u32
  WGR_COLOR_WHITE* = 0xFFFFFFFF'u32
  WGR_COLOR_BLACK* = 0x000000FF'u32
  WGR_COLOR_BLANK* = 0x00000000'u32
  WGR_COLOR_MAGENTA* = 0xFF00FFFF'u32
  WGR_COLOR_RAYWHITE* = 0xF5F5F5FF'u32
  WGR_INPUT_MAX_TOUCHES* = 8.cint
  WGR_INPUT_MAX_GAMEPADS* = 4.cint
  WGR_KEYBOARD_MAX_KEYS* = 512.cint
  WGR_KEYBOARD_MAX_PRESSED_KEYS* = 32.cint
  WGR_KEYBOARD_MAX_PRESSED_CHARS* = 32.cint
  WGR_VERSION_MAJOR* = 0.cint
  WGR_VERSION_MINOR* = 0.cint
  WGR_VERSION_PATCH* = 1.cint
  WGR_VERSION_HAS_LABEL* = 1.cint
  WGR_WINDOW_FLAG_FULLSCREEN_MODE* = 0x00000002'u32
  WGR_WINDOW_FLAG_WINDOW_RESIZABLE* = 0x00000004'u32
  WGR_WINDOW_FLAG_WINDOW_UNDECORATED* = 0x00000008'u32
  WGR_WINDOW_FLAG_WINDOW_TRANSPARENT* = 0x00000010'u32
  WGR_WINDOW_FLAG_MSAA_4X_HINT* = 0x00000020'u32
  WGR_WINDOW_FLAG_VSYNC_OFF* = 0x00000040'u32
  WGR_WINDOW_FLAG_WINDOW_HIDDEN* = 0x00000080'u32
  WGR_WINDOW_FLAG_LOW_DPI* = 0x00002000'u32

{.push importc, cdecl, header: "wgr.h".}

proc wgr_asset_set_host*(host: cstring)
proc wgr_asset_get_host*(): cstring
proc wgr_asset_set_cache_dir*(dir: cstring): bool
proc wgr_asset_set_fetcher*(fn: WgrAssetFetchFn; user_data: pointer): bool
proc wgr_asset_fetch_done*(request: WgrHandle; ok: bool): bool
proc wgr_asset_evict*(path: cstring): bool
proc wgr_asset_clear_cache*()
proc wgr_asset_ensure_async*(path: cstring; fetch_url: cstring; flags: cuint): WgrHandle
proc wgr_asset_add_task*(task: WgrHandle; on_success: WgrAssetCallbackFn; on_failure: WgrAssetCallbackFn; user_data: pointer): cint
proc wgr_asset_group_create*(): WgrHandle
proc wgr_asset_group_add*(group: WgrHandle; task: WgrHandle): bool
proc wgr_asset_get_progress*(task: WgrHandle): cfloat
proc wgr_asset_add_redirect*(prefix: cstring; target: cstring): bool
proc wgr_asset_clear_redirects*()
proc wgr_asset_ping_host*(host: cstring; timeout_ms: cint; on_done: WgrAssetPingFn; user_data: pointer): bool
proc wgr_asset_set_upload_budget*(milliseconds: cfloat)
proc wgr_audio_create*(path: cstring): WgrHandle
proc wgr_audio_release*(handle: WgrHandle)
proc wgr_camera3d_create*(projection: cint): WgrHandle
proc wgr_camera3d_get_default*(): WgrHandle
proc wgr_camera3d_destroy*(camera: WgrHandle)
proc wgr_camera3d_set_view*(camera: WgrHandle; position_x: cfloat; position_y: cfloat; position_z: cfloat; target_x: cfloat; target_y: cfloat; target_z: cfloat; up_x: cfloat; up_y: cfloat; up_z: cfloat): bool
proc wgr_camera3d_set_projection*(camera: WgrHandle; projection: cint): bool
proc wgr_camera3d_get_projection*(camera: WgrHandle): cint
proc wgr_camera3d_set_fov*(camera: WgrHandle; fov: cfloat): bool
proc wgr_camera3d_get_fov*(camera: WgrHandle): cfloat
proc wgr_camera3d_set_ortho_height*(camera: WgrHandle; height: cfloat): bool
proc wgr_camera3d_get_ortho_height*(camera: WgrHandle): cfloat
proc wgr_camera3d_set_active*(camera: WgrHandle): bool
proc wgr_camera3d_get_active*(): WgrHandle
proc wgr_color_rgba*(r: cint; g: cint; b: cint; a: cint): WgrColor
proc wgr_color_rgbaf*(r: cfloat; g: cfloat; b: cfloat; a: cfloat): WgrColor
proc wgr_color_with_alpha*(color: WgrColor; a: cint): WgrColor
proc wgr_color_get_red*(color: WgrColor): cint
proc wgr_color_get_green*(color: WgrColor): cint
proc wgr_color_get_blue*(color: WgrColor): cint
proc wgr_color_get_alpha*(color: WgrColor): cint
proc wgr_color_lerp*(`from`: WgrColor; to: WgrColor; t: cfloat): WgrColor
proc wgr_debug_enable_fps*(x: cint; y: cint; font_size: cint)
proc wgr_debug_disable_fps*()
proc wgr_environment_create*(path: cstring): WgrHandle
proc wgr_environment_release*(environment: WgrHandle)
proc wgr_event_on*(event_name: cstring; listener: WgrEventListenerFn; user_data: pointer): cint
proc wgr_event_once*(event_name: cstring; listener: WgrEventListenerFn; user_data: pointer): cint
proc wgr_event_off*(event_name: cstring; listener: WgrEventListenerFn; user_data: pointer): cint
proc wgr_event_off_all*(event_name: cstring): cint
proc wgr_event_emit*(event_name: cstring; payload: pointer): cint
proc wgr_event_listener_count*(event_name: cstring): cint
proc wgr_font_create*(path: cstring): WgrHandle
proc wgr_font_release*(handle: WgrHandle)
proc wgr_handle_get_kind*(handle: WgrHandle): cint
proc wgr_input_capture_cursor*()
proc wgr_input_release_cursor*()
proc wgr_input_get_mouse_position*(): CVec2
proc wgr_input_get_mouse_delta*(): CVec2
proc wgr_input_get_mouse_wheel*(): cfloat
proc wgr_input_get_mouse_wheel_x*(): cfloat
proc wgr_input_get_mouse_button*(button: cint): cint
proc wgr_input_get_mouse_state*(): CMouseState
proc wgr_input_get_key*(key: cint): cint
proc wgr_input_get_keyboard_state*(): CKeyboardState
proc wgr_input_get_touch_count*(): cint
proc wgr_input_get_touch*(index: cint): CTouch
proc wgr_input_get_touch_gesture*(): CTouchGesture
proc wgr_input_is_gamepad_connected*(pad: cint): bool
proc wgr_input_get_gamepad_name*(pad: cint): cstring
proc wgr_input_get_gamepad_button*(pad: cint; button: cint): cint
proc wgr_input_get_gamepad_axis*(pad: cint; axis: cint): cfloat
proc wgr_input_set_gamepad_deadzone*(radius: cfloat): bool
proc wgr_input_is_pointer_captured*(): bool
proc wgr_input_set_pointer_captured*(captured: bool)
proc wgr_input_is_keyboard_captured*(): bool
proc wgr_input_set_keyboard_captured*(captured: bool)
proc wgr_light_create*(`type`: cint): WgrHandle
proc wgr_light_destroy*(light: WgrHandle)
proc wgr_light_set_color*(light: WgrHandle; color: WgrColor): bool
proc wgr_light_set_intensity*(light: WgrHandle; intensity: cfloat): bool
proc wgr_light_set_position*(light: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_light_set_direction*(light: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_light_set_range*(light: WgrHandle; range: cfloat): bool
proc wgr_light_set_spot_cone*(light: WgrHandle; inner_angle: cfloat; outer_angle: cfloat): bool
proc wgr_light_set_enabled*(light: WgrHandle; enabled: bool): bool
proc wgr_light_is_enabled*(light: WgrHandle): bool
proc wgr_light_get_type*(light: WgrHandle): cint
proc wgr_light_get_color*(light: WgrHandle): WgrColor
proc wgr_light_get_intensity*(light: WgrHandle): cfloat
proc wgr_light_get_position*(light: WgrHandle): CVec3
proc wgr_light_get_direction*(light: WgrHandle): CVec3
proc wgr_light_get_range*(light: WgrHandle): cfloat
proc wgr_light_get_spot_inner_angle*(light: WgrHandle): cfloat
proc wgr_light_get_spot_outer_angle*(light: WgrHandle): cfloat
proc wgr_light_set_casts_shadows*(light: WgrHandle; casts: bool): bool
proc wgr_light_get_casts_shadows*(light: WgrHandle): bool
proc wgr_light_set_shadow_distance*(light: WgrHandle; distance: cfloat): bool
proc wgr_light_set_shadow_map_size*(light: WgrHandle; size: cint): bool
proc wgr_light_set_shadow_strength*(light: WgrHandle; strength: cfloat): bool
proc wgr_light_set_shadow_color*(light: WgrHandle; color: WgrColor): bool
proc wgr_light_set_shadow_bias*(light: WgrHandle; constant: cfloat; slope: cfloat): bool
proc wgr_light_get_shadow_distance*(light: WgrHandle): cfloat
proc wgr_light_get_shadow_map_size*(light: WgrHandle): cint
proc wgr_light_get_shadow_strength*(light: WgrHandle): cfloat
proc wgr_light_get_shadow_color*(light: WgrHandle): WgrColor
proc wgr_light_get_shadow_bias_constant*(light: WgrHandle): cfloat
proc wgr_light_get_shadow_bias_slope*(light: WgrHandle): cfloat
proc wgr_logger_set_level*(level: cint)
proc wgr_logger_message*(level: cint; format: cstring) {.varargs.}
proc wgr_logger_message_source*(level: cint; source_file: cstring; source_line: cint; format: cstring) {.varargs.}
proc wgr_texture_get_default*(): WgrHandle
proc wgr_texture_get_placeholder*(): WgrHandle
proc wgr_texture_set_placeholder*(texture: WgrHandle): bool
proc wgr_texture_create*(path: cstring): WgrHandle
proc wgr_texture_create_target*(width: cint; height: cint): WgrHandle
proc wgr_texture_set_sampling*(texture: WgrHandle; wrap_u: cint; wrap_v: cint; filter: cint): bool
proc wgr_texture_get_size*(handle: WgrHandle): CVec2
proc wgr_texture_draw*(texture: WgrHandle; x: cfloat; y: cfloat; width: cfloat; height: cfloat; tint: WgrColor)
proc wgr_texture_draw_ex*(texture: WgrHandle; source_x: cfloat; source_y: cfloat; source_width: cfloat; source_height: cfloat; x: cfloat; y: cfloat; width: cfloat; height: cfloat; tint: WgrColor)
proc wgr_texture_draw_nine_slice*(texture: WgrHandle; source_x: cfloat; source_y: cfloat; source_width: cfloat; source_height: cfloat; left: cfloat; top: cfloat; right: cfloat; bottom: cfloat; x: cfloat; y: cfloat; width: cfloat; height: cfloat; tint: WgrColor)
proc wgr_texture_release*(handle: WgrHandle)
proc wgr_material_create*(shading: cint): WgrHandle
proc wgr_material_create_custom*(shader: WgrHandle): WgrHandle
proc wgr_material_get_shader*(material: WgrHandle): WgrHandle
proc wgr_material_release*(material: WgrHandle)
proc wgr_material_set_shading*(material: WgrHandle; shading: cint): bool
proc wgr_material_get_shading*(material: WgrHandle): cint
proc wgr_material_set_alpha_mode*(material: WgrHandle; mode: cint; cutoff: cfloat): bool
proc wgr_material_get_alpha_mode*(material: WgrHandle): cint
proc wgr_material_set_double_sided*(material: WgrHandle; double_sided: bool): bool
proc wgr_material_is_double_sided*(material: WgrHandle): bool
proc wgr_material_set_int*(material: WgrHandle; name: cstring; value: cint): bool
proc wgr_material_set_float*(material: WgrHandle; name: cstring; value: cfloat): bool
proc wgr_material_set_vec2*(material: WgrHandle; name: cstring; x: cfloat; y: cfloat): bool
proc wgr_material_set_vec3*(material: WgrHandle; name: cstring; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_material_set_vec4*(material: WgrHandle; name: cstring; x: cfloat; y: cfloat; z: cfloat; w: cfloat): bool
proc wgr_material_set_color*(material: WgrHandle; name: cstring; color: WgrColor): bool
proc wgr_material_set_texture*(material: WgrHandle; name: cstring; texture: WgrHandle): bool
proc wgr_material_set_texture_sampling*(material: WgrHandle; name: cstring; wrap_u: cint; wrap_v: cint; filter: cint): bool
proc wgr_mesh_create*(path: cstring): WgrHandle
proc wgr_mesh_release*(mesh: WgrHandle)
proc wgr_mesh_create_plane*(width: cfloat; length: cfloat; subdivisions: cint): WgrHandle
proc wgr_mesh_create_cube*(width: cfloat; height: cfloat; length: cfloat): WgrHandle
proc wgr_mesh_create_sphere*(radius: cfloat; rings: cint; segments: cint): WgrHandle
proc wgr_mesh_create_cylinder*(radius: cfloat; height: cfloat; segments: cint): WgrHandle
proc wgr_mesh_create_cone*(radius: cfloat; height: cfloat; segments: cint): WgrHandle
proc wgr_mesh_create_capsule*(radius: cfloat; height: cfloat; rings: cint; segments: cint): WgrHandle
proc wgr_mesh_create_torus*(radius: cfloat; thickness: cfloat; rings: cint; segments: cint): WgrHandle
proc wgr_mesh_get_material_count*(mesh: WgrHandle): cint
proc wgr_mesh_get_material*(mesh: WgrHandle; slot: cint): WgrHandle
proc wgr_model_create*(mesh: WgrHandle): WgrHandle
proc wgr_model_set_mesh*(handle: WgrHandle; mesh: WgrHandle): bool
proc wgr_model_set_transform*(handle: WgrHandle; position_x: cfloat; position_y: cfloat; position_z: cfloat; rotation_x: cfloat; rotation_y: cfloat; rotation_z: cfloat; scale_x: cfloat; scale_y: cfloat; scale_z: cfloat): bool
proc wgr_model_set_position*(handle: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_model_set_rotation*(handle: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_model_set_scale*(handle: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_model_get_position*(handle: WgrHandle): CVec3
proc wgr_model_get_rotation*(handle: WgrHandle): CVec3
proc wgr_model_get_scale*(handle: WgrHandle): CVec3
proc wgr_model_set_tint*(handle: WgrHandle; color: WgrColor): bool
proc wgr_model_set_material*(handle: WgrHandle; slot: cint; material: WgrHandle): bool
proc wgr_model_get_material*(handle: WgrHandle; slot: cint): WgrHandle
proc wgr_model_set_visible*(handle: WgrHandle; visible: bool): bool
proc wgr_model_is_visible*(handle: WgrHandle): bool
proc wgr_model_set_pickable*(handle: WgrHandle; pickable: bool): bool
proc wgr_model_is_pickable*(handle: WgrHandle): bool
proc wgr_model_set_enabled*(model: WgrHandle; enabled: bool): bool
proc wgr_model_is_enabled*(model: WgrHandle): bool
proc wgr_model_set_casts_shadow*(model: WgrHandle; casts: bool): bool
proc wgr_model_casts_shadow*(model: WgrHandle): bool
proc wgr_model_set_receives_shadow*(model: WgrHandle; receives: bool): bool
proc wgr_model_receives_shadow*(model: WgrHandle): bool
proc wgr_model_draw*(handle: WgrHandle)
proc wgr_model_destroy*(handle: WgrHandle)
proc wgr_model_get_animation_count*(handle: WgrHandle): cint
proc wgr_model_set_animation*(handle: WgrHandle; animation_index: cint): bool
proc wgr_model_set_animation_speed*(handle: WgrHandle; speed: cfloat): bool
proc wgr_model_set_animation_loop*(handle: WgrHandle; loop: bool): bool
proc wgr_model_animate*(handle: WgrHandle; delta_seconds: cfloat): bool
proc wgr_model_set_animation_time*(handle: WgrHandle; seconds: cfloat): bool
proc wgr_model_get_animation_time*(handle: WgrHandle): cfloat
proc wgr_model_get_animation_duration*(handle: WgrHandle; animation_index: cint): cfloat
proc wgr_model_is_ready*(handle: WgrHandle): bool
proc wgr_pick_object*(`object`: WgrHandle; camera: WgrHandle; x: cfloat; y: cfloat): CPickResult
proc wgr_pick_get_stats*(): CPickStats
proc wgr_pick_reset_stats*()
proc wgr_render_begin_frame*()
proc wgr_render_end_frame*()
proc wgr_render_clear_background*(color: WgrColor)
proc wgr_render_begin_mode_2d*()
proc wgr_render_end_mode_2d*()
proc wgr_render_begin_mode_3d*()
proc wgr_render_end_mode_3d*()
proc wgr_render_push_clip*(x: cfloat; y: cfloat; width: cfloat; height: cfloat)
proc wgr_render_pop_clip*()
proc wgr_render_begin_texture*(texture: WgrHandle): bool
proc wgr_render_end_texture*()
proc wgr_render_add_effect*(material: WgrHandle): bool
proc wgr_render_clear_effects*()
proc wgr_render_effect_count*(): cint
proc wgr_scene_create*(): WgrHandle
proc wgr_scene_destroy*(scene: WgrHandle)
proc wgr_scene_add*(scene: WgrHandle; drawable: WgrHandle; layer: cint): bool
proc wgr_scene_set_layer*(scene: WgrHandle; drawable: WgrHandle; layer: cint): bool
proc wgr_scene_remove*(scene: WgrHandle; drawable: WgrHandle): bool
proc wgr_scene_clear*(scene: WgrHandle)
proc wgr_scene_set_clip*(scene: WgrHandle; layer: cint; x: cfloat; y: cfloat; width: cfloat; height: cfloat): bool
proc wgr_scene_set_active_camera*(scene: WgrHandle; camera: WgrHandle)
proc wgr_scene_set_ambient*(scene: WgrHandle; color: WgrColor; intensity: cfloat): bool
proc wgr_scene_set_environment*(scene: WgrHandle; environment: WgrHandle; intensity: cfloat; rotation: cfloat): bool
proc wgr_scene_set_background*(scene: WgrHandle; environment: WgrHandle; blur: cfloat): bool
proc wgr_scene_set_tonemap*(scene: WgrHandle; tonemap: cint; exposure: cfloat): bool
proc wgr_scene_draw*(scene: WgrHandle)
proc wgr_scene_set_interactive*(scene: WgrHandle; interactive: bool): bool
proc wgr_scene_set_culling*(scene: WgrHandle; culling: bool): bool
proc wgr_scene_is_culling*(scene: WgrHandle): bool
proc wgr_scene_is_interactive*(scene: WgrHandle): bool
proc wgr_scene_get_hovered*(scene: WgrHandle): WgrHandle
proc wgr_scene_get_hover*(scene: WgrHandle; `object`: WgrHandle): cint
proc wgr_scene_get_press*(scene: WgrHandle; `object`: WgrHandle): cint
proc wgr_scene_is_clicked*(scene: WgrHandle; `object`: WgrHandle): bool
proc wgr_scene_pick*(scene: WgrHandle; camera: WgrHandle; mouse_x: cfloat; mouse_y: cfloat): CPickResult
proc wgr_shader_create*(path: cstring): WgrHandle
proc wgr_shader_release*(shader: WgrHandle)
proc wgr_shape2d_draw_rectangle*(x: cfloat; y: cfloat; width: cfloat; height: cfloat; color: WgrColor)
proc wgr_shape2d_draw_rectangle_lines*(x: cfloat; y: cfloat; width: cfloat; height: cfloat; color: WgrColor)
proc wgr_shape2d_draw_line*(start_x: cfloat; start_y: cfloat; end_x: cfloat; end_y: cfloat; color: WgrColor)
proc wgr_shape2d_draw_circle*(center_x: cfloat; center_y: cfloat; radius: cfloat; color: WgrColor)
proc wgr_shape2d_draw_circle_lines*(center_x: cfloat; center_y: cfloat; radius: cfloat; color: WgrColor)
proc wgr_shape2d_draw_triangle*(x0: cfloat; y0: cfloat; x1: cfloat; y1: cfloat; x2: cfloat; y2: cfloat; color: WgrColor)
proc wgr_shape2d_draw_rounded_rectangle*(x: cfloat; y: cfloat; width: cfloat; height: cfloat; r_top_left: cfloat; r_top_right: cfloat; r_bottom_right: cfloat; r_bottom_left: cfloat; color: WgrColor)
proc wgr_shape2d_draw_border*(x: cfloat; y: cfloat; width: cfloat; height: cfloat; left: cfloat; top: cfloat; right: cfloat; bottom: cfloat; r_top_left: cfloat; r_top_right: cfloat; r_bottom_right: cfloat; r_bottom_left: cfloat; color: WgrColor)
proc wgr_shape2d_create*(): WgrHandle
proc wgr_shape2d_destroy*(shape: WgrHandle)
proc wgr_shape2d_set_rectangle*(shape: WgrHandle; width: cfloat; height: cfloat; corner_radius: cfloat): bool
proc wgr_shape2d_set_circle*(shape: WgrHandle; radius: cfloat): bool
proc wgr_shape2d_set_line*(shape: WgrHandle; x0: cfloat; y0: cfloat; x1: cfloat; y1: cfloat; thickness: cfloat): bool
proc wgr_shape2d_set_transform*(shape: WgrHandle; x: cfloat; y: cfloat; rotation: cfloat; scale_x: cfloat; scale_y: cfloat): bool
proc wgr_shape2d_set_position*(shape: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_shape2d_set_rotation*(shape: WgrHandle; angle: cfloat): bool
proc wgr_shape2d_set_scale*(shape: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_shape2d_get_position*(shape: WgrHandle): CVec2
proc wgr_shape2d_get_rotation*(shape: WgrHandle): cfloat
proc wgr_shape2d_get_scale*(shape: WgrHandle): CVec2
proc wgr_shape2d_set_pivot*(shape: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_shape2d_set_outline*(shape: WgrHandle; thickness: cfloat): bool
proc wgr_shape2d_set_color*(shape: WgrHandle; color: WgrColor): bool
proc wgr_shape2d_set_visible*(shape: WgrHandle; visible: bool): bool
proc wgr_shape2d_is_visible*(shape: WgrHandle): bool
proc wgr_shape2d_set_pickable*(shape: WgrHandle; pickable: bool): bool
proc wgr_shape2d_is_pickable*(shape: WgrHandle): bool
proc wgr_shape2d_set_enabled*(shape: WgrHandle; enabled: bool): bool
proc wgr_shape2d_is_enabled*(shape: WgrHandle): bool
proc wgr_shape2d_draw*(shape: WgrHandle)
proc wgr_shape3d_draw_line*(x0: cfloat; y0: cfloat; z0: cfloat; x1: cfloat; y1: cfloat; z1: cfloat; color: WgrColor)
proc wgr_shape3d_draw_cube*(cx: cfloat; cy: cfloat; cz: cfloat; width: cfloat; height: cfloat; length: cfloat; color: WgrColor)
proc wgr_shape3d_draw_cube_wires*(cx: cfloat; cy: cfloat; cz: cfloat; width: cfloat; height: cfloat; length: cfloat; color: WgrColor)
proc wgr_shape3d_draw_sphere*(cx: cfloat; cy: cfloat; cz: cfloat; radius: cfloat; color: WgrColor)
proc wgr_shape3d_draw_grid*(slices: cint; spacing: cfloat; color: WgrColor)
proc wgr_shape3d_draw_rectangle*(cx: cfloat; cy: cfloat; cz: cfloat; width: cfloat; height: cfloat; rx: cfloat; ry: cfloat; rz: cfloat; color: WgrColor)
proc wgr_shape3d_draw_circle*(cx: cfloat; cy: cfloat; cz: cfloat; radius: cfloat; rx: cfloat; ry: cfloat; rz: cfloat; color: WgrColor)
proc wgr_shape3d_create*(): WgrHandle
proc wgr_shape3d_destroy*(shape: WgrHandle)
proc wgr_shape3d_set_cube*(shape: WgrHandle; width: cfloat; height: cfloat; length: cfloat): bool
proc wgr_shape3d_set_sphere*(shape: WgrHandle; radius: cfloat): bool
proc wgr_shape3d_set_rectangle*(shape: WgrHandle; width: cfloat; height: cfloat): bool
proc wgr_shape3d_set_circle*(shape: WgrHandle; radius: cfloat): bool
proc wgr_shape3d_set_line*(shape: WgrHandle; x0: cfloat; y0: cfloat; z0: cfloat; x1: cfloat; y1: cfloat; z1: cfloat): bool
proc wgr_shape3d_set_line_strip*(shape: WgrHandle): bool
proc wgr_shape3d_add_point*(shape: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_shape3d_get_point_count*(shape: WgrHandle): cint
proc wgr_shape3d_set_transform*(shape: WgrHandle; position_x: cfloat; position_y: cfloat; position_z: cfloat; rotation_x: cfloat; rotation_y: cfloat; rotation_z: cfloat; scale_x: cfloat; scale_y: cfloat; scale_z: cfloat): bool
proc wgr_shape3d_set_position*(handle: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_shape3d_set_rotation*(handle: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_shape3d_set_scale*(handle: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_shape3d_get_position*(handle: WgrHandle): CVec3
proc wgr_shape3d_get_rotation*(handle: WgrHandle): CVec3
proc wgr_shape3d_get_scale*(handle: WgrHandle): CVec3
proc wgr_shape3d_set_color*(shape: WgrHandle; color: WgrColor): bool
proc wgr_shape3d_set_visible*(shape: WgrHandle; visible: bool): bool
proc wgr_shape3d_is_visible*(shape: WgrHandle): bool
proc wgr_shape3d_set_pickable*(shape: WgrHandle; pickable: bool): bool
proc wgr_shape3d_is_pickable*(shape: WgrHandle): bool
proc wgr_shape3d_set_enabled*(shape: WgrHandle; enabled: bool): bool
proc wgr_shape3d_is_enabled*(shape: WgrHandle): bool
proc wgr_shape3d_draw*(shape: WgrHandle)
proc wgr_sound_create*(audio: WgrHandle): WgrHandle
proc wgr_sound_set_audio*(handle: WgrHandle; audio: WgrHandle): bool
proc wgr_sound_destroy*(handle: WgrHandle)
proc wgr_sound_play*(handle: WgrHandle): bool
proc wgr_sound_pause*(handle: WgrHandle): bool
proc wgr_sound_resume*(handle: WgrHandle): bool
proc wgr_sound_stop*(handle: WgrHandle): bool
proc wgr_sound_set_loop*(handle: WgrHandle; loop: bool): bool
proc wgr_sound_set_volume*(handle: WgrHandle; volume: cfloat): bool
proc wgr_sound_set_pitch*(handle: WgrHandle; pitch: cfloat): bool
proc wgr_sound_set_pan*(handle: WgrHandle; pan: cfloat): bool
proc wgr_sound_is_playing*(handle: WgrHandle): bool
proc wgr_emitter2d_create*(texture: WgrHandle): WgrHandle
proc wgr_emitter2d_destroy*(emitter: WgrHandle)
proc wgr_emitter2d_set_source*(emitter: WgrHandle; x: cfloat; y: cfloat; width: cfloat; height: cfloat): bool
proc wgr_emitter2d_set_frames*(emitter: WgrHandle; columns: cint; rows: cint; count: cint; per_second: cfloat): bool
proc wgr_emitter2d_set_position*(emitter: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_emitter2d_jump*(emitter: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_emitter2d_get_position*(emitter: WgrHandle): CVec2
proc wgr_emitter2d_set_rate*(emitter: WgrHandle; per_second: cfloat): bool
proc wgr_emitter2d_burst*(emitter: WgrHandle; count: cint): bool
proc wgr_emitter2d_set_emitting*(emitter: WgrHandle; emitting: bool): bool
proc wgr_emitter2d_is_emitting*(emitter: WgrHandle): bool
proc wgr_emitter2d_set_max*(emitter: WgrHandle; count: cint): bool
proc wgr_emitter2d_set_life*(emitter: WgrHandle; min_seconds: cfloat; max_seconds: cfloat): bool
proc wgr_emitter2d_prewarm*(emitter: WgrHandle; seconds: cfloat): bool
proc wgr_emitter2d_set_spawn_box*(emitter: WgrHandle; half_width: cfloat; half_height: cfloat): bool
proc wgr_emitter2d_set_spawn_circle*(emitter: WgrHandle; radius: cfloat): bool
proc wgr_emitter2d_set_velocity*(emitter: WgrHandle; x: cfloat; y: cfloat; spread: cfloat; speed_variance: cfloat): bool
proc wgr_emitter2d_set_gravity*(emitter: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_emitter2d_set_drag*(emitter: WgrHandle; per_second: cfloat): bool
proc wgr_emitter2d_set_inherit_velocity*(emitter: WgrHandle; fraction: cfloat): bool
proc wgr_emitter2d_set_size*(emitter: WgrHandle; start: cfloat; `end`: cfloat; variance: cfloat): bool
proc wgr_emitter2d_set_color*(emitter: WgrHandle; start: WgrColor; `end`: WgrColor): bool
proc wgr_emitter2d_add_size_key*(emitter: WgrHandle; t: cfloat; size: cfloat): bool
proc wgr_emitter2d_clear_size_keys*(emitter: WgrHandle): bool
proc wgr_emitter2d_add_color_key*(emitter: WgrHandle; t: cfloat; color: WgrColor): bool
proc wgr_emitter2d_clear_color_keys*(emitter: WgrHandle): bool
proc wgr_emitter2d_add_palette_color*(emitter: WgrHandle; color: WgrColor): bool
proc wgr_emitter2d_clear_palette*(emitter: WgrHandle): bool
proc wgr_emitter2d_set_spin*(emitter: WgrHandle; min: cfloat; max: cfloat): bool
proc wgr_emitter2d_set_stretch*(emitter: WgrHandle; seconds: cfloat): bool
proc wgr_emitter2d_set_alpha_mode*(emitter: WgrHandle; mode: cint; cutoff: cfloat): bool
proc wgr_emitter2d_set_seed*(emitter: WgrHandle; seed: cuint): bool
proc wgr_emitter2d_get_count*(emitter: WgrHandle): cint
proc wgr_emitter2d_clear*(emitter: WgrHandle)
proc wgr_emitter2d_set_visible*(emitter: WgrHandle; visible: bool): bool
proc wgr_emitter2d_draw*(emitter: WgrHandle)
proc wgr_emitter3d_create*(texture: WgrHandle): WgrHandle
proc wgr_emitter3d_destroy*(emitter: WgrHandle)
proc wgr_emitter3d_set_source*(emitter: WgrHandle; x: cfloat; y: cfloat; width: cfloat; height: cfloat): bool
proc wgr_emitter3d_set_frames*(emitter: WgrHandle; columns: cint; rows: cint; count: cint; per_second: cfloat): bool
proc wgr_emitter3d_set_position*(emitter: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_emitter3d_jump*(emitter: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_emitter3d_get_position*(emitter: WgrHandle): CVec3
proc wgr_emitter3d_set_rate*(emitter: WgrHandle; per_second: cfloat): bool
proc wgr_emitter3d_burst*(emitter: WgrHandle; count: cint): bool
proc wgr_emitter3d_set_emitting*(emitter: WgrHandle; emitting: bool): bool
proc wgr_emitter3d_is_emitting*(emitter: WgrHandle): bool
proc wgr_emitter3d_set_max*(emitter: WgrHandle; count: cint): bool
proc wgr_emitter3d_set_life*(emitter: WgrHandle; min_seconds: cfloat; max_seconds: cfloat): bool
proc wgr_emitter3d_prewarm*(emitter: WgrHandle; seconds: cfloat): bool
proc wgr_emitter3d_set_spawn_box*(emitter: WgrHandle; half_x: cfloat; half_y: cfloat; half_z: cfloat): bool
proc wgr_emitter3d_set_spawn_sphere*(emitter: WgrHandle; radius: cfloat): bool
proc wgr_emitter3d_set_velocity*(emitter: WgrHandle; x: cfloat; y: cfloat; z: cfloat; spread: cfloat; speed_variance: cfloat): bool
proc wgr_emitter3d_set_gravity*(emitter: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_emitter3d_set_drag*(emitter: WgrHandle; per_second: cfloat): bool
proc wgr_emitter3d_set_inherit_velocity*(emitter: WgrHandle; fraction: cfloat): bool
proc wgr_emitter3d_set_size*(emitter: WgrHandle; start: cfloat; `end`: cfloat; variance: cfloat): bool
proc wgr_emitter3d_set_color*(emitter: WgrHandle; start: WgrColor; `end`: WgrColor): bool
proc wgr_emitter3d_add_size_key*(emitter: WgrHandle; t: cfloat; size: cfloat): bool
proc wgr_emitter3d_clear_size_keys*(emitter: WgrHandle): bool
proc wgr_emitter3d_add_color_key*(emitter: WgrHandle; t: cfloat; color: WgrColor): bool
proc wgr_emitter3d_clear_color_keys*(emitter: WgrHandle): bool
proc wgr_emitter3d_add_palette_color*(emitter: WgrHandle; color: WgrColor): bool
proc wgr_emitter3d_clear_palette*(emitter: WgrHandle): bool
proc wgr_emitter3d_set_spin*(emitter: WgrHandle; min: cfloat; max: cfloat): bool
proc wgr_emitter3d_set_stretch*(emitter: WgrHandle; seconds: cfloat): bool
proc wgr_emitter3d_set_alpha_mode*(emitter: WgrHandle; mode: cint; cutoff: cfloat): bool
proc wgr_emitter3d_set_seed*(emitter: WgrHandle; seed: cuint): bool
proc wgr_emitter3d_get_count*(emitter: WgrHandle): cint
proc wgr_emitter3d_clear*(emitter: WgrHandle)
proc wgr_emitter3d_set_visible*(emitter: WgrHandle; visible: bool): bool
proc wgr_emitter3d_draw*(emitter: WgrHandle)
proc wgr_sprite2d_create*(texture: WgrHandle): WgrHandle
proc wgr_sprite2d_destroy*(sprite: WgrHandle)
proc wgr_sprite2d_set_texture*(sprite: WgrHandle; texture: WgrHandle): bool
proc wgr_sprite2d_set_source*(sprite: WgrHandle; x: cfloat; y: cfloat; width: cfloat; height: cfloat): bool
proc wgr_sprite2d_set_transform*(sprite: WgrHandle; x: cfloat; y: cfloat; rotation: cfloat; scale_x: cfloat; scale_y: cfloat): bool
proc wgr_sprite2d_set_position*(sprite: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_sprite2d_set_rotation*(sprite: WgrHandle; angle: cfloat): bool
proc wgr_sprite2d_set_scale*(sprite: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_sprite2d_get_position*(sprite: WgrHandle): CVec2
proc wgr_sprite2d_get_rotation*(sprite: WgrHandle): cfloat
proc wgr_sprite2d_get_scale*(sprite: WgrHandle): CVec2
proc wgr_sprite2d_set_size*(sprite: WgrHandle; width: cfloat; height: cfloat): bool
proc wgr_sprite2d_set_pivot*(sprite: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_sprite2d_set_nine_slice*(sprite: WgrHandle; left: cfloat; top: cfloat; right: cfloat; bottom: cfloat): bool
proc wgr_sprite2d_set_tint*(sprite: WgrHandle; color: WgrColor): bool
proc wgr_sprite2d_set_visible*(sprite: WgrHandle; visible: bool): bool
proc wgr_sprite2d_is_visible*(sprite: WgrHandle): bool
proc wgr_sprite2d_set_pickable*(sprite: WgrHandle; pickable: bool): bool
proc wgr_sprite2d_is_pickable*(sprite: WgrHandle): bool
proc wgr_sprite2d_set_enabled*(sprite: WgrHandle; enabled: bool): bool
proc wgr_sprite2d_is_enabled*(sprite: WgrHandle): bool
proc wgr_sprite2d_set_alpha_mode*(sprite: WgrHandle; mode: cint; cutoff: cfloat): bool
proc wgr_sprite2d_get_alpha_mode*(sprite: WgrHandle): cint
proc wgr_sprite2d_set_material*(sprite: WgrHandle; material: WgrHandle): bool
proc wgr_sprite2d_get_material*(sprite: WgrHandle): WgrHandle
proc wgr_sprite2d_set_pick_alpha_test*(sprite: WgrHandle; enable: bool; threshold: cfloat): bool
proc wgr_sprite2d_draw*(sprite: WgrHandle)
proc wgr_sprite3d_create*(texture: WgrHandle): WgrHandle
proc wgr_sprite3d_set_texture*(handle: WgrHandle; texture: WgrHandle): bool
proc wgr_sprite3d_set_transform*(handle: WgrHandle; position_x: cfloat; position_y: cfloat; position_z: cfloat; rotation_x: cfloat; rotation_y: cfloat; rotation_z: cfloat; scale_x: cfloat; scale_y: cfloat; scale_z: cfloat): bool
proc wgr_sprite3d_set_position*(handle: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_sprite3d_set_rotation*(handle: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_sprite3d_set_scale*(handle: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_sprite3d_set_size*(handle: WgrHandle; size: cfloat): bool
proc wgr_sprite3d_set_extent*(handle: WgrHandle; width: cfloat; height: cfloat): bool
proc wgr_sprite3d_set_source*(handle: WgrHandle; x: cfloat; y: cfloat; width: cfloat; height: cfloat): bool
proc wgr_sprite3d_set_pivot*(handle: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_sprite3d_set_facing*(handle: WgrHandle; facing: cint): bool
proc wgr_sprite3d_get_position*(handle: WgrHandle): CVec3
proc wgr_sprite3d_get_rotation*(handle: WgrHandle): CVec3
proc wgr_sprite3d_get_scale*(handle: WgrHandle): CVec3
proc wgr_sprite3d_set_tint*(handle: WgrHandle; color: WgrColor): bool
proc wgr_sprite3d_set_visible*(handle: WgrHandle; visible: bool): bool
proc wgr_sprite3d_is_visible*(handle: WgrHandle): bool
proc wgr_sprite3d_set_pickable*(handle: WgrHandle; pickable: bool): bool
proc wgr_sprite3d_is_pickable*(handle: WgrHandle): bool
proc wgr_sprite3d_set_enabled*(sprite: WgrHandle; enabled: bool): bool
proc wgr_sprite3d_is_enabled*(sprite: WgrHandle): bool
proc wgr_sprite3d_set_alpha_mode*(handle: WgrHandle; mode: cint; cutoff: cfloat): bool
proc wgr_sprite3d_get_alpha_mode*(handle: WgrHandle): cint
proc wgr_sprite3d_set_material*(handle: WgrHandle; material: WgrHandle): bool
proc wgr_sprite3d_get_material*(handle: WgrHandle): WgrHandle
proc wgr_sprite3d_set_pick_alpha_test*(handle: WgrHandle; enable: bool; threshold: cfloat): bool
proc wgr_sprite3d_draw*(handle: WgrHandle)
proc wgr_sprite3d_destroy*(handle: WgrHandle)
proc wgr_text_set_default_font*(font: WgrHandle): bool
proc wgr_text_get_default_font*(): WgrHandle
proc wgr_text_draw_fps*(x: cint; y: cint)
proc wgr_text_draw_fps_ex*(font: WgrHandle; x: cfloat; y: cfloat; size: cfloat; color: WgrColor)
proc wgr_text_draw*(text: cstring; x: cint; y: cint; font_size: cint; color: WgrColor)
proc wgr_text_measure*(text: cstring; font_size: cint): cint
proc wgr_text_draw_ex*(font: WgrHandle; text: cstring; x: cfloat; y: cfloat; size: cfloat; color: WgrColor)
proc wgr_text_measure_ex*(font: WgrHandle; text: cstring; size: cfloat): CVec2
proc wgr_text_draw_n*(font: WgrHandle; text: cstring; length: cint; x: cfloat; y: cfloat; size: cfloat; color: WgrColor)
proc wgr_text_measure_n*(font: WgrHandle; text: cstring; length: cint; size: cfloat): CVec2
proc wgr_text2d_create*(font: WgrHandle): WgrHandle
proc wgr_text2d_set_font*(handle: WgrHandle; font: WgrHandle): bool
proc wgr_text2d_set_text*(handle: WgrHandle; text: cstring): bool
proc wgr_text2d_set_position*(handle: WgrHandle; x: cfloat; y: cfloat): bool
proc wgr_text2d_get_position*(handle: WgrHandle): CVec2
proc wgr_text2d_set_size*(handle: WgrHandle; size: cfloat): bool
proc wgr_text2d_set_color*(handle: WgrHandle; color: WgrColor): bool
proc wgr_text2d_set_visible*(handle: WgrHandle; visible: bool): bool
proc wgr_text2d_is_visible*(handle: WgrHandle): bool
proc wgr_text2d_set_pickable*(handle: WgrHandle; pickable: bool): bool
proc wgr_text2d_is_pickable*(handle: WgrHandle): bool
proc wgr_text2d_set_enabled*(text: WgrHandle; enabled: bool): bool
proc wgr_text2d_is_enabled*(text: WgrHandle): bool
proc wgr_text2d_set_align*(handle: WgrHandle; horizontal: cint; vertical: cint): bool
proc wgr_text2d_set_max_width*(handle: WgrHandle; width: cfloat): bool
proc wgr_text2d_measure_width*(handle: WgrHandle): cfloat
proc wgr_text2d_measure_height*(handle: WgrHandle): cfloat
proc wgr_text2d_draw*(handle: WgrHandle)
proc wgr_text2d_destroy*(handle: WgrHandle)
proc wgr_text3d_create*(font: WgrHandle): WgrHandle
proc wgr_text3d_destroy*(text: WgrHandle)
proc wgr_text3d_set_font*(text: WgrHandle; font: WgrHandle): bool
proc wgr_text3d_set_text*(text: WgrHandle; string: cstring): bool
proc wgr_text3d_set_size*(text: WgrHandle; size: cfloat): bool
proc wgr_text3d_set_align*(text: WgrHandle; horizontal: cint; vertical: cint): bool
proc wgr_text3d_set_max_width*(text: WgrHandle; width: cfloat): bool
proc wgr_text3d_set_transform*(text: WgrHandle; x: cfloat; y: cfloat; z: cfloat; rotation_x: cfloat; rotation_y: cfloat; rotation_z: cfloat): bool
proc wgr_text3d_set_position*(text: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_text3d_set_rotation*(text: WgrHandle; x: cfloat; y: cfloat; z: cfloat): bool
proc wgr_text3d_get_position*(text: WgrHandle): CVec3
proc wgr_text3d_get_rotation*(text: WgrHandle): CVec3
proc wgr_text3d_set_facing*(text: WgrHandle; facing: cint): bool
proc wgr_text3d_set_color*(text: WgrHandle; color: WgrColor): bool
proc wgr_text3d_set_visible*(text: WgrHandle; visible: bool): bool
proc wgr_text3d_is_visible*(text: WgrHandle): bool
proc wgr_text3d_set_pickable*(text: WgrHandle; pickable: bool): bool
proc wgr_text3d_is_pickable*(text: WgrHandle): bool
proc wgr_text3d_set_enabled*(text: WgrHandle; enabled: bool): bool
proc wgr_text3d_is_enabled*(text: WgrHandle): bool
proc wgr_text3d_get_size*(text: WgrHandle): CVec2
proc wgr_text3d_draw*(text: WgrHandle)
proc wgr_text_draw_3d*(font: WgrHandle; text: cstring; x: cfloat; y: cfloat; z: cfloat; size: cfloat; color: WgrColor)
proc wgr_version_major*(): cint
proc wgr_version_minor*(): cint
proc wgr_version_patch*(): cint
proc wgr_version_label*(): cstring
proc wgr_version_number*(): cuint
proc wgr_version_string*(): cstring
proc wgr_window_set_title*(title: cstring)
proc wgr_window_close_requested*(): cint
proc wgr_window_get_screen_size*(): CVec2
proc wgr_window_set_size*(width: cint; height: cint): bool
proc wgr_window_set_position*(x: cint; y: cint): bool
proc wgr_window_get_position*(): CVec2
proc wgr_window_has_fullscreen*(): bool
proc wgr_window_request_fullscreen*(fullscreen: bool): bool
proc wgr_window_is_fullscreen*(): bool
proc wgr_window_set_visible*(visible: bool): bool
proc wgr_window_is_visible*(): bool
proc wgr_window_is_focused*(): bool
proc wgr_window_get_monitor_count*(): cint
proc wgr_window_get_monitor*(): cint
proc wgr_window_set_monitor*(monitor: cint): bool
proc wgr_window_get_monitor_size*(monitor: cint): CVec2
proc wgr_window_get_monitor_position*(monitor: cint): CVec2
proc wgr_window_get_monitor_name*(monitor: cint): cstring
proc wgr_init_values*(window_width: cint; window_height: cint; window_title: cstring; window_flags: cuint): cint
proc wgr_set_frame*(frame_fn: WgrFrameFn; user_data: pointer)
proc wgr_set_tick*(tick_fn: WgrTickFn; user_data: pointer; hz: cint)
proc wgr_set_init*(init_fn: WgrLifecycleFn; user_data: pointer)
proc wgr_set_cleanup*(cleanup_fn: WgrLifecycleFn; user_data: pointer)
proc wgr_run*(): cint
proc wgr_request_quit*()
proc wgr_is_initialized*(): bool
proc wgr_get_platform*(): cstring
proc wgr_get_renderer*(): cstring
proc wgr_has_threads*(): bool
proc wgr_set_target_fps*(fps: cint)
proc wgr_get_time*(): cdouble

{.pop.}
